cepums_src = [
    'Disassembler.cpp',
    'Log.cpp',
    'Main.cpp',
    'Memory.cpp',
    'Processor/Processor.cpp',
    'Processor/ProcessorUtils.cpp',
    'Processor/Register.cpp',
    'Utilities/ELFUtils.cpp',
]

cepums = executable('cepums-alpha', cepums_src, dependencies: [fmt_dep, spdlog_dep])