#pragma once

#include <cstdint>

namespace Cepums {

enum class Instruction {
    Invalid,
    CallPal,
    LDA,
    LDAH,
    BR,
    LDBU,
    LDQ_U,
    LDWU,
    STW,
    STB,
    STQ_U,

    INTA, // Uses function field, actual instructions are right after this:
    ADDL,
    S4ADDL,
    SUBL,
    S8ADDL,
    S8SUBQ,
    ADDQ,
    S4ADDQ,
    SUBQ,
    S8ADDQ,
    ADDL_V,
    SUBL_V,
    ADDQ_V,
    S4SUBL,
    CMPBGE,
    CMPULT,
    S4SUBQ,
    CMPEQ,
    CMPULE,
    CMPLT,
    CMPLE,
    SUBQ_V,

    INTL, // Uses function field, actual instructions are right after this:
    AND,
    BIC,
    CMOVLBS,
    CMOVLBC,
    BIS,
    CMOVEQ,
    CMOVNE,
    ORNOT,
    XOR,
    CMOVLT,
    CMOVGE,
    EQV,
    CMOVLE,
    CMOVGT,
    IMPLVER,

    INTS, // Uses function field, actual instructions are right after this:
    MSKBL,
    EXTBL,
    INSBL,
    MSKWL,
    EXTWL,
    INSWL,
    MSKLL,
    EXTLL,
    INSLL,
    ZAP,
    ZAPNOT,
    MSKQL,
    SRL,
    EXTQL,
    SLL,
    INSQL,
    SRA,
    MSKWH,
    INSWH,
    EXTWH,
    MSKLH,
    INSLH,
    EXTLH,
    MSKQH,
    INSQH,
    EXTQH,

    INTM, // Uses function field, actual instructions are right after this:
    MULL,
    MULQ,
    UMULH,
    MULL_V,
    MULQ_V,

    ITFP, // Uses function field, actual instructions are right after this:
    ITOFS,
    ITOFF,
    ITOFT,
    SQRTF,
    SQRTS,
    SQRTG,
    SQRTT,

    FLTV, // Uses function field, actual instructions are right after this:
    ADDF,
    SUBF,
    MULF,
    DIVF,
    CVTDG,
    ADDG,
    SUBG,
    MULG,
    DIVG,
    CMPGEQ,
    CMPGLT,
    CMPGLE,
    CVTGF,
    CVTGD,
    CVTGQ,
    CVTQF,
    CVTQG,

    FLTI, // Uses function field, actual instructions are right after this:
    ADDS,
    SUBS,
    MULS,
    DIVS,
    ADDT,
    SUBT,
    MULT,
    DIVT,
    CMPTUN,
    CMPTEQ,
    CMPTLT,
    CMPTLE,
    CVTTS,
    CVTTQ,
    CVTQS,
    CVTQT,
    CVTST,

    FLTL, // Uses function field, actual instructions are right after this:
    CVTLQ,
    CPYS,
    CPYSN,
    CPYSE,
    MT_FPCR,
    MF_FPCR,
    FCMOVEQ,
    FCMOVNE,
    FCMOVLT,
    FCMOVGE,
    FCMOVLE,
    FCMOVGT,
    CVTQL,

    MISC, // Uses function field, actual instructions are right after this:
    TRAPB,
    MB,
    WMB,
    FETCH,
    FETCH_M,
    RPCC,
    RC,
    RS,
    WH64,
    WH64EN,

    PAL2,
    JSR,
    PAL3,

    FPTI, // Uses function field, actual instructions are right after this:
    SEXTB,
    SEXTW,
    CTPOP,
    PERR,
    CTLZ,
    CTTZ,
    UNPKBW,
    UNPKBL,
    PKWB,
    PKLB,
    MINSB8,
    MINSW4,
    MINUB8,
    MINUW4,
    MAXUB8,
    MAXUW4,
    MAXSB8,
    MAXSW4,
    FTOIT,
    FTOIS,

    MTPR,
    PAL4,
    PAL5,
    LDF,
    LDG,
    LDS,
    LDT,
    STF,
    STG,
    STS,
    STT,
    LDL,
    LDQ,
    LDL_L,
    LDQ_L,
    STL,
    STQ,
    STL_C,
    STQ_C,
    FBEQ,
    FBLT,
    FBLE,
    BSR,
    FBNE,
    FBGE,
    FBGT,
    BLBC,
    BEQ,
    BLT,
    BLE,
    BLBS,
    BNE,
    BGE,
    BGT,
};

enum class InstructionFormat { Invalid, Memory, Branch, Operate, FloatPointOperate, PALcode };

Instruction decodeInstruction(uint8_t opcode);

InstructionFormat instructionFormat(Instruction instruction);

} // namespace Cepums
